### ISSUE TITLE
design animation page

### ISSUE THREAD

**Issue by SarahPalmer-co** [zuri-training/team-93_anime-lib#10]
Animations page
This is where the list of animations will be and there will be a preview of the animations

**Comment by ToniaReuben** [comment]
**Tonia Reuben** - Figjam (Affinity map, Idea prioritization matrix) - https://www.figma.com/file/QtStjtF3X9i9NSfhzNiTbc/Anim8?node-id=0%3A1

**Tonia Reuben** - Figma board (Landing page UX copy, Lowfi Animation page, Hifi Animation page, animation button drop down, style guide buttons - https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=2%3A2

**Tonia Reuben** - Research plan document - https://docs.google.com/document/d/1-KIyB7aD1OxDLhqqFpN2dBa8e6mXJong9-cy7DiT27g/edit?usp=sharing

**Tonia Reuben** - Research survey - https://forms.gle/82qMboHrYe4wi9LG8

**Comment by Etunim** [comment]
Noted

**Comment by AnuoluwaAdeyiga** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=1494%3A4724

**Comment by Etunim** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=1494%3A4724

**Comment by ToniaReuben** [comment]
Task completed.
