### ISSUE TITLE
presentation scripting

### ISSUE THREAD

**Issue by SarahPalmer-co** [zuri-training/team-93_anime-lib#12]

**Comment by EmmanuelaBruce** [comment]
[https://docs.google.com/document/d/1YGFS_bGqt-sY-j-50hglaL874pN3gHHy66OoFt-NZOI/edit?usp=sharing](url) Scripting draft

**Comment by Goziem1274** [comment]
Presentation slides
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=295%3A599
