### ISSUE TITLE
animation page 

### ISSUE THREAD

**Issue by ghost** [zuri-training/team-93_anime-lib#15]

**Comment by emmanuelakinj** [comment]
https://github.com/zuri-training/team-93_anime-lib/tree/main/Animation%20page(authorized)

**Comment by emmanuelakinj** [comment]
https://github.com/zuri-training/team-93_anime-lib/tree/main/Animation%20page(unauthorized)

**Comment by akinlope** [comment]
added after effect to the animation page buttons

**Comment by akinlope** [comment]
added after effect to the animation page buttons
