### ISSUE TITLE
design landing page

### ISSUE THREAD

**Issue by SarahPalmer-co** [zuri-training/team-93_anime-lib#6]
Landing Page
The Landing page is the very first page when entering the platform. It will have the header that has the navigation and the search bar. The page's footer should have a contact us where we have links to socials, email and also an about us section that shows the platform's team. In the main section of the landing page, there will be a list of animations and a preview of what each animation will look like. This is also where the login and register buttons will be for the users. There could also be a demo of what some animations look like.

**Comment by EmmanuelaBruce** [comment]
[https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=481%3A631](url) - high fi 
[https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=2%3A3](url) low fi

Changes to the landing page was made

**Comment by Ajayi-Ifeoluwa** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=2%3A3 - Low Fidelity design

https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=481%3A631 - High Fidelity design

**Comment by Ajayi-Ifeoluwa** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=2%3A3 - Low Fi design

https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=481%3A631 - High Fidelity design

**Comment by ehikash** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=2%3A3 - Low Fidelity

https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631 - High Fidelity

**Comment by mcbarbieA** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631 - HighFi
