### ISSUE TITLE
design documentation page

### ISSUE THREAD

**Issue by SarahPalmer-co** [zuri-training/team-93_anime-lib#7]
Documentations page
The document containing the information for this will be sent but there should be a page for this page. It should contain a comment section and ratings for the documentation asking if the information was useful?

[https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=481%3A631](https://github.com/orgs/zuri-training/projects/106/views/url)

**Comment by AdebankeUX** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631

**Contains all documentations made.**

**Comment by IraborA** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631

**Comment by mcbarbieA** [comment]
Designed the rating , input and comments of the Documentations page -https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631

**Comment by mcbarbieA** [comment]
Task completed.
