### ISSUE TITLE
authentication page

### ISSUE THREAD

**Issue by SarahPalmer-co** [zuri-training/team-93_anime-lib#9]
Registration Page/ Sign Up
This is the registration page that will give unauthenticated users access to our library and the ability to download the library. It should include a form that asks for the following information;
First Name
Last Name
Username
Email Address
Password
Re-type/Confirm password
There should be a button linking to the login page and there should be the option of signing in with google and Github.
Login Page
This will be a rather simple page where the authenticated users will log in. It will include a form asking for;
Username/Email Address
Password
It will have a forgot password button and also a button linking to the sign-up page.

**Comment by Goziem1274** [comment]
https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=2%3A3

https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Anim8?node-id=481%3A631

The lo-fi and hi-fi accordingly

**Comment by SarahPalmer-co** [comment]
https://www.figma.com/file/znIPR9a0DOkHe9woJdqEGE/Team93_animelib-(Copy)?node-id=1494%3A4795

**Comment by SarahPalmer-co** [comment]
https://www.figma.com/file/znIPR9a0DOkHe9woJdqEGE/Team93_animelib-(Copy)?node-id=1494%3A4795

**Comment by mcbarbieA** [comment]
Designed the Sign-up, log in, forgot password and recover password pages - https://www.figma.com/file/HKPoh50TrclH1QFMildIUG/Team93_animelib?node-id=481%3A631
